rm -rf /Applications/Cydia.app
rm -rf /bin/bash
rm -rf /bin/bunzip2
rm -rf /bin/bzcat
rm -rf /bin/bzip2
rm -rf /bin/bzip2recover
rm -rf /bin/cat
rm -rf /bin/chgrp
rm -rf /bin/chmod
rm -rf /bin/chown
rm -rf /bin/cp
rm -rf /bin/date
rm -rf /bin/dd
rm -rf /bin/dir
rm -rf /bin/echo
rm -rf /bin/egrep
rm -rf /bin/false
rm -rf /bin/fgrep
rm -rf /bin/grep
rm -rf /bin/gtar
rm -rf /bin/gunzip
rm -rf /bin/gzexe
rm -rf /bin/gzip
rm -rf /bin/kill
rm -rf /bin/ln
rm -rf /bin/ls
rm -rf /bin/mkdir
rm -rf /bin/mknod
rm -rf /bin/mktemp
rm -rf /bin/mv
rm -rf /bin/pwd
rm -rf /bin/readlink
rm -rf /bin/rm
rm -rf /bin/rmdir
rm -rf /bin/run-parts
rm -rf /bin/sed
rm -rf /bin/sh
rm -rf /bin/sleep
rm -rf /bin/stty
rm -rf /bin/su
rm -rf /bin/sync
rm -rf /bin/tar
rm -rf /bin/touch
rm -rf /bin/true
rm -rf /bin/uname
rm -rf /bin/uncompress
rm -rf /bin/vdir
rm -rf /bin/zcat
rm -rf /bin/zcmp
rm -rf /bin/zdiff
rm -rf /bin/zegrep
rm -rf /bin/zfgrep
rm -rf /bin/zforce
rm -rf /bin/zgrep
rm -rf /bin/zless
rm -rf /bin/zmore
rm -rf /bin/znew
rm -rf /Library/dpkg
rm -rf /Library/LaunchDaemons/com.openssh.sshd.plist
rm -rf /Library/LaunchDaemons/com.saurik.Cydia.Startup.plist
rm -rf /private/etc/apt
rm -rf /private/etc/alternatives/README
rm -rf /private/etc/dpkg
rm -rf /private/etc/profile
rm -rf /private/etc/profile.d/terminal.sh
rm -rf /private/etc/ssh/
rm -rf /private/etc/ssl/certs
rm -rf /private/etc/ssl/openssl.cnf
rm -rf /private/var/cache/apt
rm -rf /private/var/lib/apt
rm -rf /private/var/lib/cydia
rm -rf /private/var/lib/dpkg
rm -rf /private/var/log/apt
rm -rf /s/bin/dmesg
rm -rf /s/bin/dynamic_pager
rm -rf /s/bin/halt
rm -rf /s/bin/nologin
rm -rf /s/bin/reboot
rm -rf /s/bin/update_dyld_shared_cache
rm -rf /usr//bin/bash
rm -rf /usr//bin/bunzip2
rm -rf /usr//bin/bzcat
rm -rf /usr//bin/bzip2
rm -rf /usr//bin/bzip2recover
rm -rf /usr//bin/cat
rm -rf /usr//bin/chgrp
rm -rf /usr//bin/chmod
rm -rf /usr//bin/chown
rm -rf /usr//bin/cp
rm -rf /usr//bin/date
rm -rf /usr//bin/dd
rm -rf /usr//bin/dir
rm -rf /usr//bin/echo
rm -rf /usr//bin/egrep
rm -rf /usr//bin/false
rm -rf /usr//bin/fgrep
rm -rf /usr//bin/grep
rm -rf /usr//bin/gtar
rm -rf /usr//bin/gunzip
rm -rf /usr//bin/gzexe
rm -rf /usr//bin/gzip
rm -rf /usr//bin/kill
rm -rf /usr//bin/ln
rm -rf /usr//bin/ls
rm -rf /usr//bin/mkdir
rm -rf /usr//bin/mknod
rm -rf /usr//bin/mktemp
rm -rf /usr//bin/mv
rm -rf /usr//bin/pwd
rm -rf /usr//bin/readlink
rm -rf /usr//bin/rm
rm -rf /usr//bin/rmdir
rm -rf /usr//bin/run-parts
rm -rf /usr//bin/sed
rm -rf /usr//bin/sh
rm -rf /usr//bin/sleep
rm -rf /usr//bin/stty
rm -rf /usr//bin/su
rm -rf /usr//bin/sync
rm -rf /usr//bin/tar
rm -rf /usr//bin/touch
rm -rf /usr//bin/true
rm -rf /usr//bin/uname
rm -rf /usr//bin/uncompress
rm -rf /usr//bin/vdir
rm -rf /usr//bin/zcat
rm -rf /usr//bin/zcmp
rm -rf /usr//bin/zdiff
rm -rf /usr//bin/zegrep
rm -rf /usr//bin/zfgrep
rm -rf /usr//bin/zforce
rm -rf /usr//bin/zgrep
rm -rf /usr//bin/zless
rm -rf /usr//bin/zmore
rm -rf /usr//bin/znew
rm -rf /usr//bin/dpkg*
rm -rf /usr//bin/db*
rm -rf /usr/include/curses.h
rm -rf /usr/include/db*
rm -rf /usr/include/dpkg
rm -rf /usr/include/eti.h
rm -rf /usr/include/form.h
rm -rf /usr/include/lzma
rm -rf /usr/include/lzma.h
rm -rf /usr/include/menu.h
rm -rf /usr/include/nc_tparam.h
rm -rf /usr/include/nc_tparm.h
rm -rf /usr/include/ncurses_dll.h
rm -rf /usr/include/ncurses.h
rm -rf /usr/include/openssl
rm -rf /usr/include/lzma
rm -rf /usr/include/panel.h
rm -rf /usr/include/term*
rm -rf /usr/include/tic.h
rm -rf /usr/include/unctrl.h
rm -rf /usr/lib/pkgconfig
rm -rf /usr/lib/ssl
rm -rf /usr/lib/terminfo
rm -rf /usr/lib/libdpkg*
rm -rf /usr/lib/libssl*
rm -rf /usr/lib/libdb*
rm -rf /usr/lib/libform*
rm -rf /usr/lib/liblzma*
rm -rf /usr/lib/libmenu*
rm -rf /usr/lib/libncurses*
rm -rf /usr/lib/libpanel*
rm -rf /usr/lib/apt
rm -rf /usr/lib/bash
rm -rf /usr/lib/engines
rm -rf /usr/lib/libapt*
rm -rf /usr/lib/libcrypto*
rm -rf /usr/lib/libcurses.a
rm -rf /usr/libexec/apt
rm -rf /usr/libexec/cydia
rm -rf /usr/libexec/dpkg
rm -rf /usr/libexec/gnupg
rm -rf /usr/libexec/bigram
rm -rf /usr/libexec/code
rm -rf /usr/libexec/frcode
rm -rf /usr/libexec/rmt
rm -rf /usr/libexec/ssh*
rm -rf /usr/libexec/sftp-server
rm -rf /usr/local/lib/liblzma*
rm -rf /usr//s/bin/ac
rm -rf /usr//s/bin/accton
rm -rf /usr//s/bin/halt
rm -rf /usr//s/bin/iostat
rm -rf /usr//s/bin/mkfile
rm -rf /usr//s/bin/pwd_mkdb
rm -rf /usr//s/bin/reboot
rm -rf /usr//s/bin/sshd
rm -rf /usr//s/bin/startupfiletool
rm -rf /usr//s/bin/sysctl
rm -rf /usr//s/bin/vifs
rm -rf /usr//s/bin/vipw
rm -rf /usr//s/bin/zdump
rm -rf /usr/share/bash-completion/completions/apt
rm -rf /usr/share/bigboss
rm -rf /usr/share/doc/apt
rm -rf /usr/share/dpkg
rm -rf /usr/share/gnupg
